### ISSUE TITLE
Mountain Mixture is missing. 

### ISSUE THREAD

**Issue by James-E-Adams** [DerFlatulator/bob-ross#1]
Hi,

I was following along to Bob Ross and trying to implement one of his interfaces in node, and stumbled upon your package. This is great! But, you seem to be missing Mountain Mixture. 

When I get a second away from painting, I'l fork this delightful repo and add it in for future users.

Cheers,

James

**Comment by azz** [comment]
Mountain Mixture is a mixture of Phthalo Blue and Titanium White. Use your favorite color library to mix the two.
